export const BookData = {
    status: "ok",
    querys: [
        {
            mId: 836169,
            title: "許石的臺灣歌 /",
            isbns: "9789862744048",
            authors: "林哲璋",
            publishers: "臺南市政府出版 ; ",
            externalCoverUrl: "http://static.findbook.tw/image/book/9862744049/large",
            keyword: "臺灣民謠,許石",
            counts: 7,
            placeOfPublication: "臺南市 :",
            year: "2018.06",
            languages: "[NT]",
            recordType: "書目-語言資料,印刷品",
            itemCount: 28,
            availableItemCountForLoan: 23,
            items: [
                {
                    itemId: 3810620,
                    itemNumber: "31507001891180",
                    locationName: "A_JB-市圖兒童書區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 4451 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "送回原館藏地",
                    dateReceived: "2018/06/22",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 4158351,
                    itemNumber: "31507001898482",
                    locationName: "A_JB-市圖兒童書區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 4451 2018 c.1",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/10/22",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 3859058,
                    itemNumber: "31519001037094",
                    locationName: "M-臺南文化中心藝文沙龍",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 8745 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 3810618,
                    itemNumber: "AML0004836",
                    locationName: "ML_T-許石臺灣音樂區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 4451 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/06/22",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    opacNote: "臺灣音樂1",
                    allowReserve: "1"
                },
                {
                    itemId: 3859040,
                    itemNumber: "AP0022635",
                    locationName: "B_NB-安平年度新書區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 4451 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "修補中",
                    dateReceived: "2018/09/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "0"
                },
                {
                    itemId: 3859043,
                    itemNumber: "AT0017077",
                    locationName: "E_JB-土城兒童書區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 4451 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 3859042,
                    itemNumber: "DS0103734",
                    locationName: "DS_JB-東山兒童書區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 8745 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 3859044,
                    itemNumber: "ED0123834",
                    locationName: "ED_JB-安定兒童書區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 8745 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 3859047,
                    itemNumber: "KL0091306",
                    locationName: "KL_JB-佳里兒童書區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 8745 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 3859048,
                    itemNumber: "KM0131375",
                    locationName: "KM_JB-關廟兒童書區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.6033 8745 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 3859049,
                    itemNumber: "KT0116654",
                    locationName: "KT_JB-官田兒童書區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 8745 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "借出",
                    dateReceived: "2018/09/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1",
                    dueDate: "2020/12/22"
                },
                {
                    itemId: 3859050,
                    itemNumber: "KZ0193111",
                    locationName: "KZ_JB-歸仁兒童書區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 8745 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    opacNote: "366",
                    allowReserve: "1"
                },
                {
                    itemId: 3859051,
                    itemNumber: "LC0077240",
                    locationName: "LC_JB-龍崎兒童書區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.6033 8745 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 3859045,
                    itemNumber: "LS0032751",
                    locationName: "F-1-東區林森圖書館",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 4451 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 3859060,
                    itemNumber: "NC0077566",
                    locationName: "NC_JB-楠西兒童書區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 8745 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 3830319,
                    itemNumber: "NY0038494",
                    locationName: "G2_JB-鹽埕兒童書區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 4451 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/08/03",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 3859052,
                    itemNumber: "RJ0047997",
                    locationName: "RJ_B-蕭壠開架閱覽區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 8745 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 4190226,
                    itemNumber: "RR0002668",
                    locationName: "HS-南瀛國際人文研究中心",
                    itemClassName: "不外借",
                    materialType: "南瀛人文中心用書",
                    callNumber: "RR 913.533 4451 2018.6",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/11/27",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 3859053,
                    itemNumber: "SH0119715",
                    locationName: "SH_MC-新化多元文化區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 8745 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 3859059,
                    itemNumber: "SS0028897",
                    locationName: "G_JB-喜樹兒童書區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 4451 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 3859054,
                    itemNumber: "TC0055801",
                    locationName: "TC_JB-左鎮兒童書區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 8745 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 3859061,
                    itemNumber: "TJ0006272",
                    locationName: "TJ_JB-台江文化中心兒童書區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 4451 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 3842768,
                    itemNumber: "TN0143347",
                    locationName: "TN_JB-新營文化中心兒童書區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 8745 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/08/03",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 3859055,
                    itemNumber: "TN0194896",
                    locationName: "TN_JB-新營文化中心兒童書區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.6033 8745 2018 c.1",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 3977065,
                    itemNumber: "TPL0190435",
                    locationName: "TPL_JPA-新總館B1兒童區-繪本區（故事）",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.6033 4451 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "編目處理中",
                    dateReceived: "2019/01/03",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    staffNote: "開館後請送館發組改分類號913.533",
                    allowReserve: "0"
                },
                {
                    itemId: 4056352,
                    itemNumber: "TPL0271353",
                    locationName: "TPL_JPA-新總館B1兒童區-繪本區（故事）",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.6033 4451 2018 c.2",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "編目處理中",
                    dateReceived: "2019/05/31",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    staffNote: "開館後請送館發組改分類號913.533",
                    allowReserve: "0"
                },
                {
                    itemId: 4056353,
                    itemNumber: "TPL0273887",
                    locationName: "TPL_JPA-新總館B1兒童區-繪本區（故事）",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.6033 4451 2018 c.1",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "編目處理中",
                    dateReceived: "2019/05/31",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    staffNote: "開館後請送館發組改分類號913.533",
                    allowReserve: "0"
                },
                {
                    itemId: 4410825,
                    itemNumber: "TPL0378130",
                    locationName: "TPL_VP-新總館2F視障資料區",
                    itemClassName: "不外借",
                    materialType: "視障資料",
                    callNumber: "VB 913.533 4451 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "編目處理中",
                    dateReceived: "2020/10/05",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    opacNote: "雙視書",
                    allowReserve: "0"
                },
                {
                    itemId: 3859041,
                    itemNumber: "WC0019985",
                    locationName: "D_JB-中西兒童書區",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 4451 2018",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 4258857,
                    itemNumber: "WC0024237",
                    locationName: "D_HSO-中西罕用書庫（需線上調閱）",
                    itemClassName: "可借14天",
                    materialType: "兒童書",
                    callNumber: "J 913.533 4451 2018 c.1",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/04/12",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                }
            ]
        },
        {
            mId: 76864,
            title: "五線譜上的許石 /",
            isbns: "9789869187909",
            authors: "許朝欽",
            publishers: "華風文化,",
            externalCoverUrl: "http://static.findbook.tw/image/book/9869187900/large",
            keyword: "作曲家,音樂家,臺灣傳記,許石",
            counts: 7,
            placeOfPublication: "新北市 :",
            year: "2015.06",
            languages: "[NT]",
            recordType: "書目-語言資料,印刷品",
            itemCount: 45,
            availableItemCountForLoan: 38,
            items: [
                {
                    itemId: 434477,
                    itemNumber: "31204005695342",
                    locationName: "ML_G-許石音樂總論區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 0848 2015 c.1",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2015/12/31",
                    cclSubject: "藝術類→音樂→音樂總論",
                    staffNote: "附1光碟",
                    opacNote: "音樂總論2",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3944369,
                    itemNumber: "31519001040312",
                    locationName: "M-臺南文化中心藝文沙龍",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8449 2015",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/12/26",
                    cclSubject: "藝術類→音樂→音樂總論",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 434478,
                    itemNumber: "AML0000983",
                    locationName: "ML_G-許石音樂總論區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 0810 2015",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2015/12/30",
                    cclSubject: "藝術類→音樂→音樂總論",
                    opacNote: "音樂總論2",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4437438,
                    itemNumber: "AML0015111",
                    locationName: "ML_G-許石音樂總論區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 0810 2015 c.2",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "編目處理中",
                    dateReceived: "2020/11/08",
                    cclSubject: "藝術類→音樂→音樂總論",
                    opacNote: "音樂總論2",
                    allowReserve: "0"
                },
                {
                    itemId: 3844892,
                    itemNumber: "AN0025337",
                    locationName: "C_B-安南開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 0848 2015",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/08/22",
                    cclSubject: "藝術類→音樂→音樂總論",
                    opacNote: "附1光碟",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3845362,
                    itemNumber: "AP0002002",
                    locationName: "B_B-安平開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 0810 2015",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/08/25",
                    cclSubject: "藝術類→音樂→音樂總論",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3844403,
                    itemNumber: "AT0004579",
                    locationName: "E_TA-土城南市作家作品區",
                    itemClassName: "L可借28天",
                    materialType: "南市作家作品",
                    callNumber: "TA 910.9933 0848 2015",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/08/18",
                    cclSubject: "藝術類→音樂→音樂總論",
                    staffNote: "附1光碟",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4329360,
                    itemNumber: "AZ0006112",
                    locationName: "Z_B-安南行動圖書館開架閱覽區",
                    itemClassName: "可借14天",
                    materialType: "中文書",
                    callNumber: "910.9933 0810 2015",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/07/12",
                    cclSubject: "藝術類→音樂→音樂總論",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3873694,
                    itemNumber: "CK0041325",
                    locationName: "CK_B-七股開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8449 2015",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/10/18",
                    cclSubject: "藝術類→音樂→音樂總論",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3866321,
                    itemNumber: "DS0105509",
                    locationName: "DS_B-東山開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8449 2015",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/08/19",
                    cclSubject: "藝術類→音樂→音樂總論",
                    attachment: "附一光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3851284,
                    itemNumber: "ED0096974",
                    locationName: "ED_B-安定開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8449 2015",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/08/29",
                    cclSubject: "藝術類→音樂→音樂總論",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3880451,
                    itemNumber: "HK0069168",
                    locationName: "HK_B-西港開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8449",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/10/25",
                    cclSubject: "藝術類→音樂→音樂總論",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3850893,
                    itemNumber: "HY0072490",
                    locationName: "HY_B-下營開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8449 2015",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/08/19",
                    cclSubject: "藝術類→音樂→音樂總論",
                    attachment: "附一光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3864977,
                    itemNumber: "JG0061233",
                    locationName: "JG-5-將軍區圖書館",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8449",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/25",
                    cclSubject: "藝術類→音樂→音樂總論",
                    staffNote: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3864609,
                    itemNumber: "KL0093096",
                    locationName: "KL_B-佳里開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8449 2015",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/21",
                    cclSubject: "藝術類→音樂→音樂總論",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3844449,
                    itemNumber: "KT0108880",
                    locationName: "KT_B-官田開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8449 2015",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/08/18",
                    cclSubject: "藝術類→音樂→音樂總論",
                    staffNote: "附1光碟",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3844591,
                    itemNumber: "KZ0158535",
                    locationName: "KZ_B-歸仁開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8449",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/08/20",
                    cclSubject: "藝術類→音樂→音樂總論",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3844424,
                    itemNumber: "LI0078730",
                    locationName: "LI_B-柳營開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8449 2015.06",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/08/18",
                    cclSubject: "藝術類→音樂→音樂總論",
                    staffNote: "附CD一片",
                    attachment: "附CD一片",
                    allowReserve: "1"
                },
                {
                    itemId: 434479,
                    itemNumber: "LS0010242",
                    locationName: "F_B-林森開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 0848 2015",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2015/12/31",
                    cclSubject: "藝術類→音樂→音樂總論",
                    staffNote: "附1光碟",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3853391,
                    itemNumber: "LS0021194",
                    locationName: "F_B-林森開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 0848 2015 c.1",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/07",
                    cclSubject: "藝術類→音樂→音樂總論",
                    staffNote: "贈書",
                    attachment: "附一光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3948191,
                    itemNumber: "NC0077830",
                    locationName: "NC_B-楠西開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8449 2015",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/12/29",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4242436,
                    itemNumber: "NC0078230",
                    locationName: "NC_B-楠西開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8449 2015 c.1",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/03/14",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 3851303,
                    itemNumber: "NY0038603",
                    locationName: "G2_B-鹽埕開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 0848 2015 c.1",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/08/29",
                    cclSubject: "藝術類→音樂→音樂總論",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3851305,
                    itemNumber: "NY0038604",
                    locationName: "G2_B-鹽埕開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 0848 2015 c.2",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/08/29",
                    cclSubject: "藝術類→音樂→音樂總論",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3851302,
                    itemNumber: "NY0038605",
                    locationName: "G2_B-鹽埕開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 0848 2015",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/08/29",
                    cclSubject: "藝術類→音樂→音樂總論",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3851087,
                    itemNumber: "PH0036322",
                    locationName: "PH_B-白河開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8449",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/08/28",
                    cclSubject: "藝術類→音樂→音樂總論",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3873350,
                    itemNumber: "PM0037919",
                    locationName: "PM_B-北門開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8449",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "借出",
                    dateReceived: "2018/08/28",
                    cclSubject: "藝術類→音樂→音樂總論",
                    attachment: "附1光碟",
                    allowReserve: "1",
                    dueDate: "2021/01/05"
                },
                {
                    itemId: 3924186,
                    itemNumber: "SG0093205",
                    locationName: "SG_B-學甲開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8449 2015",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/12/11",
                    cclSubject: "藝術類→音樂→音樂總論",
                    attachment: "附一光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3844490,
                    itemNumber: "SH0082711",
                    locationName: "SH_B-新化開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8449 2015",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/08/19",
                    cclSubject: "藝術類→音樂→音樂總論",
                    attachment: "附一光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 3862324,
                    itemNumber: "SN0173570",
                    locationName: "SN-3-善化區圖書館",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8449 2015",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2018/09/19",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                }
            ]
        },
        {
            mId: 977752,
            title: "許石百歲冥誕紀念專刊 /",
            isbns: "9789860589184",
            authors: "徐玫玲",
            publishers: "傳藝中心,",
            externalCoverUrl: "http://static.findbook.tw/image/book/9860589186/large",
            keyword: "作曲家,音樂家,臺灣傳記,許石",
            counts: 7,
            placeOfPublication: "宜蘭縣五結鄉 :",
            year: "2019.01",
            languages: "[NT]",
            recordType: "書目-語言資料,印刷品",
            itemCount: 3,
            availableItemCountForLoan: 2,
            items: [
                {
                    itemId: 4142392,
                    itemNumber: "AML0010261",
                    locationName: "ML_T-許石臺灣音樂區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 2811 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "借出",
                    dateReceived: "2019/09/19",
                    cclSubject: "藝術類→音樂→音樂總論",
                    opacNote: "臺灣音樂1",
                    allowReserve: "1",
                    dueDate: "2020/12/15"
                },
                {
                    itemId: 4142395,
                    itemNumber: "AML0010262",
                    locationName: "ML_T-許石臺灣音樂區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 2811 2019 c.1",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/09/19",
                    cclSubject: "藝術類→音樂→音樂總論",
                    opacNote: "臺灣音樂1",
                    allowReserve: "1"
                },
                {
                    itemId: 4216415,
                    itemNumber: "NY0040013",
                    locationName: "G2_B-鹽埕開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 2811 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/23",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                }
            ]
        },
        {
            mId: 379886,
            title: "許石與楊三郎懷念臺灣歌謠交響詩",
            authors: "許石",
            publishers: "繆斯藝術文化,",
            externalCoverUrl: "noimage",
            keyword: "楊三郎,交響詩,許石",
            counts: 7,
            placeOfPublication: "臺北市 :",
            year: "[2015?]",
            languages: "[NT]",
            recordType: "書目-語言資料,印刷品",
            itemCount: 1,
            availableItemCountForLoan: 1,
            items: [
                {
                    itemId: 1728257,
                    itemNumber: "41204000528306",
                    locationName: "ML_T-許石臺灣音樂區",
                    itemClassName: "可借14天",
                    materialType: "DVD",
                    callNumber: "DVD 912.32 0174 2015",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2017/06/05",
                    cclSubject: "藝術類→音樂→合奏及樂團",
                    opacNote: "臺灣音樂1",
                    allowReserve: "1"
                }
            ]
        },
        {
            mId: 1000268,
            title: "百年追想曲 :",
            isbns: "9789869809092",
            authors: "黃裕元",
            publishers: "蔚藍文化 ;",
            externalCoverUrl: "http://static.findbook.tw/image/book/9869809090/large",
            keyword: "作曲家,音樂家,臺灣傳記,許石",
            counts: 7,
            placeOfPublication: "臺南市:",
            year: "2019.09",
            languages: "[NT]",
            recordType: "書目-語言資料,印刷品",
            itemCount: 36,
            availableItemCountForLoan: 33,
            items: [
                {
                    itemId: 4239757,
                    itemNumber: "AML0015127",
                    locationName: "ML_T-許石臺灣音樂區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 0810 2019 c.1",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/06/03",
                    cclSubject: "藝術類→音樂→音樂總論",
                    opacNote: "臺灣音樂1",
                    allowReserve: "1"
                },
                {
                    itemId: 4239755,
                    itemNumber: "AML0015150",
                    locationName: "ML_T-許石臺灣音樂區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 0810 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/06/03",
                    cclSubject: "藝術類→音樂→音樂總論",
                    opacNote: "臺灣音樂1",
                    allowReserve: "1"
                },
                {
                    itemId: 4194347,
                    itemNumber: "AN0025545",
                    locationName: "C_B-安南開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 4312 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/04",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4238102,
                    itemNumber: "AP0002480",
                    locationName: "B_B-安平開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 4312 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "借出",
                    dateReceived: "2020/02/24",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1",
                    dueDate: "2020/12/30"
                },
                {
                    itemId: 4208471,
                    itemNumber: "AT0005058",
                    locationName: "E_TA-土城南市作家作品區",
                    itemClassName: "L可借28天",
                    materialType: "南市作家作品",
                    callNumber: "TA 910.9933 4312 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/13",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4191601,
                    itemNumber: "CK0040894",
                    locationName: "CK_B-七股開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/11/29",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4231001,
                    itemNumber: "DS0106033",
                    locationName: "DS_B-東山開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "展覽用書(不外借)",
                    dateReceived: "2019/11/29",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "0"
                },
                {
                    itemId: 4194587,
                    itemNumber: "ED0117995",
                    locationName: "ED_SC-安定特色館藏區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/04",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4195013,
                    itemNumber: "HK0069664",
                    locationName: "HK_B-西港開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/05",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4428408,
                    itemNumber: "HP0034614",
                    locationName: "HP_NB-後壁年度新書區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/05",
                    cclSubject: "藝術類→音樂→音樂總論",
                    opacNote: "(4)",
                    allowReserve: "1"
                },
                {
                    itemId: 4206602,
                    itemNumber: "HY0072829",
                    locationName: "HY_B-下營開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/11/28",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4186935,
                    itemNumber: "JG0061662",
                    locationName: "JG_B-將軍開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/11/24",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4200546,
                    itemNumber: "KL0093758",
                    locationName: "KL_TN-佳里臺南資料區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/12",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4216416,
                    itemNumber: "KM0113196",
                    locationName: "KM_B-關廟開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/19",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4191443,
                    itemNumber: "KT0109737",
                    locationName: "KT_B-官田開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/11/28",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4295739,
                    itemNumber: "LG0082568",
                    locationName: "LG-4-六甲區圖書館",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/06/13",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4241544,
                    itemNumber: "LI0080046",
                    locationName: "LI_B-柳營開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/03/12",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4193481,
                    itemNumber: "LS0022128",
                    locationName: "F_B-林森開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 4312 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/01",
                    cclSubject: "藝術類→音樂→音樂總論",
                    staffNote: "贈書",
                    allowReserve: "1"
                },
                {
                    itemId: 4294518,
                    itemNumber: "MT0082794",
                    locationName: "MT_TN-麻豆臺南資料專區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/29",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4227574,
                    itemNumber: "NC0078046",
                    locationName: "NC_TN-楠西臺南資料專區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/29",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4195431,
                    itemNumber: "NY0039961",
                    locationName: "G2_B-鹽埕開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 4312 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/16",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4191651,
                    itemNumber: "PH0036586",
                    locationName: "PH_B-白河開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/11/29",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4230535,
                    itemNumber: "PM0038151",
                    locationName: "PM_B-北門開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "借出",
                    dateReceived: "2020/01/15",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1",
                    dueDate: "2021/01/05"
                },
                {
                    itemId: 4229956,
                    itemNumber: "SG0093443",
                    locationName: "SG_B-學甲開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/01/10",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4187196,
                    itemNumber: "SH0082967",
                    locationName: "SH_B-新化開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/11/27",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4236943,
                    itemNumber: "SN0176130",
                    locationName: "SN_B-善化開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/02/16",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4241144,
                    itemNumber: "SS0050821",
                    locationName: "G_B-喜樹開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 0810 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/03/08",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4229038,
                    itemNumber: "ST0121984",
                    locationName: "ST_B-新市開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/01/07",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4194359,
                    itemNumber: "SY0115645",
                    locationName: "SY_B-新營開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/04",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4406707,
                    itemNumber: "TC0060093",
                    locationName: "TC_B-左鎮開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 8335",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/10/02",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                }
            ]
        },
        {
            mId: 1000353,
            title: "歌謠交響 :",
            isbns: "9789865504007",
            authors: "黃裕元",
            publishers: "蔚藍文化 ;",
            externalCoverUrl: "http://static.findbook.tw/image/book/9865504006/large",
            keyword: "樂譜,臺灣,民俗音樂,許石",
            counts: 7,
            placeOfPublication: "臺南市:",
            year: "2019.11",
            languages: "[NT]",
            recordType: "書目-語言資料,印刷品",
            itemCount: 33,
            availableItemCountForLoan: 33,
            items: [
                {
                    itemId: 4239766,
                    itemNumber: "AML0015149",
                    locationName: "ML_T-許石臺灣音樂區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 0810 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/06/03",
                    cclSubject: "藝術類→音樂→音樂總論",
                    opacNote: "臺灣音樂1",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4239767,
                    itemNumber: "AML0015160",
                    locationName: "ML_T-許石臺灣音樂區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 0810 2019 c.1",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/06/03",
                    cclSubject: "藝術類→音樂→音樂總論",
                    opacNote: "臺灣音樂1",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4206705,
                    itemNumber: "AN0025550",
                    locationName: "C_B-安南開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 4431 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/13",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4274760,
                    itemNumber: "AP0002672",
                    locationName: "B_B-安平開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 4431 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/05/20",
                    cclSubject: "藝術類→音樂→音樂總論",
                    allowReserve: "1"
                },
                {
                    itemId: 4208474,
                    itemNumber: "AT0005059",
                    locationName: "E_B-土城開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 4431 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/13",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 4255675,
                    itemNumber: "CK0040795",
                    locationName: "CK_B-七股開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/03/22",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4230976,
                    itemNumber: "DS0106020",
                    locationName: "DS_B-東山開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4216932,
                    itemNumber: "ED0118028",
                    locationName: "ED_B-安定開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/24",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4233719,
                    itemNumber: "HK0069694",
                    locationName: "HK_B-西港開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/02/05",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4428407,
                    itemNumber: "HP0034613",
                    locationName: "HP_NB-後壁年度新書區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/10",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    opacNote: "(4)",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4206601,
                    itemNumber: "HY0072828",
                    locationName: "HY_B-下營開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/10",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4238182,
                    itemNumber: "JG0062121",
                    locationName: "JG_B-將軍開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/02/25",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4200547,
                    itemNumber: "KL0093759",
                    locationName: "KL_TN-佳里臺南資料區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/12",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4216425,
                    itemNumber: "KM0113199",
                    locationName: "KM_B-關廟開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/19",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4295738,
                    itemNumber: "LG0082567",
                    locationName: "LG_B-六甲開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/06/13",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4241530,
                    itemNumber: "LI0080038",
                    locationName: "LI_B-柳營開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/03/12",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 4208763,
                    itemNumber: "LS0022174",
                    locationName: "F_B-林森開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 4431 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/15",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    staffNote: "贈書",
                    allowReserve: "1"
                },
                {
                    itemId: 4294512,
                    itemNumber: "MT0082793",
                    locationName: "MT_TN-麻豆臺南資料專區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/03/12",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4227575,
                    itemNumber: "NC0078047",
                    locationName: "NC_TN-楠西臺南資料專區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/29",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4234811,
                    itemNumber: "NY0040148",
                    locationName: "G2_B-鹽埕開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 4431 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/02/09",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4200394,
                    itemNumber: "PH0036606",
                    locationName: "PH_B-白河開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4230534,
                    itemNumber: "PM0038150",
                    locationName: "PM_B-北門開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/01/15",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4229957,
                    itemNumber: "SG0093444",
                    locationName: "SG_B-學甲開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/01/10",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    allowReserve: "1"
                },
                {
                    itemId: 4200355,
                    itemNumber: "SH0082982",
                    locationName: "SH_B-新化開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/11",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4236941,
                    itemNumber: "SN0176131",
                    locationName: "SN_B-善化開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/02/16",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4241142,
                    itemNumber: "SS0050819",
                    locationName: "G_B-喜樹開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "910.9933 0810 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/03/08",
                    cclSubject: "藝術類→音樂→音樂總論",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4229042,
                    itemNumber: "ST0121985",
                    locationName: "ST_B-新市開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/01/07",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4200245,
                    itemNumber: "SY0115646",
                    locationName: "SY_B-新營開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2019/12/10",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4406706,
                    itemNumber: "TC0060092",
                    locationName: "TC_B-左鎮開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/10/02",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                },
                {
                    itemId: 4259743,
                    itemNumber: "TN0144040",
                    locationName: "TN_B-新營文化中心開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "913.533 8335 2019",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2020/04/19",
                    cclSubject: "藝術類→音樂→聲樂；歌曲",
                    attachment: "附1光碟",
                    allowReserve: "1"
                }
            ]
        },
        {
            mId: 386867,
            title: "許大同夫婦畫冊 =",
            authors: "許 大同.",
            publishers: "萬里總經銷,",
            externalCoverUrl: "noimage",
            keyword: "繪畫- 中國",
            counts: 7,
            placeOfPublication: "[香港] :",
            year: "[民81?]",
            languages: "[NT]",
            recordType: "書目-語言資料,印刷品",
            itemCount: 1,
            availableItemCountForLoan: 1,
            items: [
                {
                    itemId: 1761736,
                    itemNumber: "31204000529074",
                    locationName: "F_B-林森開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "945.5 0847 1992",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2002/11/25",
                    cclSubject: "藝術類→繪畫；書法→中國畫冊",
                    opacNote: "1992",
                    allowReserve: "1"
                }
            ]
        }
    ]
};