export const BookData = {
    status: "ok",
    querys: [
        {
            mId: 5270,
            title: "吳新榮 /",
            isbns: "9789860432602",
            authors: "吳新榮",
            publishers: "臺灣文學館,",
            externalCoverUrl: "http://static.findbook.tw/image/book/9860432600/large",
            keyword: "傳記,吳新榮,文學評論",
            counts: 43,
            placeOfPublication: "臺南市 :",
            year: "2014.12",
            languages: "[NT]",
            recordType: "書目-語言資料,印刷品",
            itemCount: 3,
            availableItemCountForLoan: 2,
            items: [
                {
                    itemId: 44933,
                    itemNumber: "31204005321683",
                    locationName: "A_B-市圖開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "863.4 4319 2014 v.55",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2015/02/13",
                    cclSubject: "語言文學類→東方文學→臺灣文學",
                    staffNote: "特色館蕆",
                    allowReserve: "1"
                },
                {
                    itemId: 44934,
                    itemNumber: "KL0086932",
                    locationName: "KL_SC-佳里特色館藏區",
                    itemClassName: "L可借28天",
                    materialType: "特色館藏",
                    callNumber: "SC 863.4 8445 2014",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2017/05/11",
                    cclSubject: "語言文學類→東方文學→臺灣文學",
                    staffNote: "特色館蕆 特色館藏",
                    opacNote: "特色館蕆",
                    allowReserve: "1"
                },
                {
                    itemId: 44935,
                    itemNumber: "KL0087653",
                    locationName: "KL_SC-佳里特色館藏區",
                    itemClassName: "L可借28天",
                    materialType: "特色館藏",
                    callNumber: "SC 863.4 8445 2014 v.55",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "借出",
                    dateReceived: "2017/08/15",
                    cclSubject: "語言文學類→東方文學→臺灣文學",
                    staffNote: "特色館蕆 特色館藏",
                    opacNote: "特色館蕆",
                    allowReserve: "1",
                    dueDate: "2020/12/17"
                }
            ]
        },
        {
            mId: 315432,
            title: "吳新榮傳/",
            isbns: "9570242965",
            authors: "施懿琳",
            publishers: "臺灣省文獻會,",
            externalCoverUrl: "http://static.findbook.tw/image/book/9789570242966/large",
            counts: 43,
            placeOfPublication: "南投市 :",
            year: "1999",
            languages: "[NT]",
            recordType: "書目-語言資料,印刷品",
            itemCount: 1,
            availableItemCountForLoan: 0,
            items: [
                {
                    itemId: 1443902,
                    itemNumber: "RR0004182",
                    locationName: "HS-南瀛國際人文研究中心",
                    itemClassName: "不外借",
                    materialType: "中文書",
                    callNumber: "783.3886 8437 1999",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2013/03/21",
                    cclSubject: "史地類：世界史地→傳記→亞洲傳記",
                    allowReserve: "1"
                }
            ]
        },
        {
            mId: 42302,
            title: "吳新榮傳 /",
            isbns: "9570242973",
            authors: "施 懿琳",
            publishers: "省文獻會,",
            externalCoverUrl: "http://static.findbook.tw/image/book/9789570242973/large",
            counts: 43,
            placeOfPublication: "南投市 :",
            year: "民88.",
            languages: "[NT]",
            recordType: "書目-語言資料,印刷品",
            itemCount: 12,
            availableItemCountForLoan: 8,
            items: [
                {
                    itemId: 292458,
                    itemNumber: "230678",
                    locationName: "TN_SC-新營文化中心特色館藏區",
                    itemClassName: "不外借",
                    materialType: "南瀛用書",
                    callNumber: "RN 782.88 8437 c.1",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2008/12/08",
                    cclSubject: "史地類：世界史地→傳記→中國傳記",
                    opacNote: "c.1",
                    allowReserve: "1"
                },
                {
                    itemId: 292438,
                    itemNumber: "378092",
                    locationName: "A_TW-市圖臺灣資料區",
                    itemClassName: "不外借",
                    materialType: "中文臺灣資料",
                    callNumber: "T 783.38 2609",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "1989/05/01",
                    cclSubject: "史地類：世界史地→傳記→亞洲傳記",
                    allowReserve: "1"
                },
                {
                    itemId: 292439,
                    itemNumber: "CK0019982",
                    locationName: "CK_XX-七股報廢專區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "781.04 8437",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "預計報廢",
                    dateReceived: "2001/10/05",
                    cclSubject: "史地類：世界史地→傳記→世界傳記",
                    allowReserve: "0"
                },
                {
                    itemId: 292440,
                    itemNumber: "ED0021745",
                    locationName: "ED_B1-安定開架閱覽區(B1)",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "782.886 8437",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "1999/12/15",
                    cclSubject: "史地類：世界史地→傳記→中國傳記",
                    allowReserve: "1"
                },
                {
                    itemId: 292441,
                    itemNumber: "HK0018086",
                    locationName: "HK_HSO-西港罕用書庫（需線上調閱）",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "781.04 8437",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2002/08/07",
                    cclSubject: "史地類：世界史地→傳記→世界傳記",
                    allowReserve: "1"
                }
            ]
        },
        {
            mId: 506693,
            title: "吳新榮書簡 /",
            authors: "吳 新榮",
            externalCoverUrl: "noimage",
            counts: 43,
            placeOfPublication: "遠景.",
            year: "1981",
            languages: "[NT]",
            recordType: "書目-語言資料,印刷品",
            itemCount: 1,
            availableItemCountForLoan: 1,
            items: [
                {
                    itemId: 2172641,
                    itemNumber: "004190",
                    locationName: "A_HSG2-市圖鹽埕罕用書區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "848.6 2609",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "1978/12/31",
                    cclSubject: "語言文學類→中國文學別集→現代別集",
                    allowReserve: "1"
                },
                {
                    itemId: 2172642,
                    itemNumber: "31204001183988",
                    locationName: "B_HSC-安平罕用書庫（閉架隱藏）",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "848.6 2609 1981",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2005/07/04",
                    cclSubject: "語言文學類→中國文學別集→現代別集",
                    opacNote: "1981",
                    allowReserve: "1"
                },
                {
                    itemId: 2172644,
                    itemNumber: "31204001183996",
                    locationName: "G_B-喜樹開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "848.6 2609 1981",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2005/07/04",
                    cclSubject: "語言文學類→中國文學別集→現代別集",
                    opacNote: "1981",
                    allowReserve: "1"
                },
                {
                    itemId: 2172643,
                    itemNumber: "31204001184002",
                    locationName: "C-1-安南區安南圖書館",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "848.6 2609 1981",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "已報廢",
                    dateReceived: "2005/07/04",
                    cclSubject: "語言文學類→中國文學別集→現代別集",
                    opacNote: "1981",
                    allowReserve: "0"
                }
            ]
        },
        {
            mId: 506706,
            title: "吳新榮日記 /",
            authors: "吳 新榮",
            externalCoverUrl: "noimage",
            counts: 43,
            placeOfPublication: "遠景.",
            year: "1981",
            languages: "[NT]",
            recordType: "書目-語言資料,印刷品",
            itemCount: 2,
            availableItemCountForLoan: 2,
            items: [
                {
                    itemId: 2172689,
                    itemNumber: "004188",
                    locationName: "A_HSG2-市圖鹽埕罕用書區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "848.6 2609",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "1978/12/31",
                    cclSubject: "語言文學類→中國文學別集→現代別集",
                    allowReserve: "1"
                },
                {
                    itemId: 2172690,
                    itemNumber: "004189",
                    locationName: "A_HSG2-市圖鹽埕罕用書區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "848.6 2609 v.2",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "1978/12/31",
                    cclSubject: "語言文學類→中國文學別集→現代別集",
                    opacNote: "v.2",
                    allowReserve: "1"
                },
                {
                    itemId: 2172691,
                    itemNumber: "31204001184010",
                    locationName: "B_HSC-安平罕用書庫（閉架隱藏）",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "848.6 2609 1981 v.戰後",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2005/07/04",
                    cclSubject: "語言文學類→中國文學別集→現代別集",
                    opacNote: "1981 v.戰後",
                    allowReserve: "1"
                },
                {
                    itemId: 2172695,
                    itemNumber: "31204001184028",
                    locationName: "G_B-喜樹開架閱覽區",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "848.6 2609 1981 v.戰後",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "在架",
                    dateReceived: "2005/07/04",
                    cclSubject: "語言文學類→中國文學別集→現代別集",
                    opacNote: "1981 v.戰後",
                    allowReserve: "1"
                },
                {
                    itemId: 2172693,
                    itemNumber: "31204001184036",
                    locationName: "C-1-安南區安南圖書館",
                    itemClassName: "L可借28天",
                    materialType: "中文書",
                    callNumber: "848.6 2609 1981 v.戰後",
                    usageClassName: "一般(Normal)",
                    inventoryStatus: "已報廢",
                    dateReceived: "2005/07/04",
                    cclSubject: "語言文學類→中國文學別集→現代別集",
                    opacNote: "1981 v.戰後",
                    allowReserve: "0"
                }
            ]
        }
    ]
};